### ISSUE TITLE
ESP mac address

### ISSUE THREAD

**Issue by austinscreations** [sumnerboy12/LSC#24]
ad ifdef for esp internal MAC address vs the external MAC address I2C chip
Other ethernet or wifi options may also be needed. due to space may be worth having a fork / separate version for ethermega and esp devices.

**Comment by sarreck** [comment]
Some more information on this one. 

When the "ENABLE_MAC_ADDRESS_ROM" is enabled the process hangs on "Getting MAC address from ROM:"

When "ENABLE_MAC_ADDRESS_ROM" is disabled the following is in the log (note, Ethernet is not connected)

`=======================
     SuperHouse.TV
Universal State Monitor
         v4.4
=======================
Watchdog NOT enabled
Scanning for devices on the I2C bus...
 - 0x20...MCP23017
 - 0x21...MCP23017
 - 0x22...MCP23017
 - 0x23...MCP23017
 - 0x24...MCP23017
 - 0x25...MCP23017
 - 0x26...empty
 - 0x27...ignored
 - 0x3C...SH1106 OLED
Getting MAC address from ROM: abled
Scanning for devices on the I2C bus...
 - 0x20...empty
 - 0x21...empty
 - 0x22...empty
 - 0x23...empty
 - 0x24...empty
 - 0x25...empty
 - 0x26...empty
 - 0x27...empty
 - 0x3C...empty
Using static MAC address: DE:AD:BE:EF:FE:ED
Getting IP address via DHCP: 255.255.255.255
MQTT client id: esp32-LSC
MQTT LWT topic: clients/esp32-LSC
`

When this is plugged into Ethernet, the DHCP server is serving an IP to the device with its actual MAC, not the software configured one. The device does not connect to MQTT. I can not show logs for this as I cannot have USB connected for logs as well as Ethernet. 


I am using a Olimex ESP32-PoE  - https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

This references the following guide for Ethernet:
https://github.com/OLIMEX/ESP32-POE/tree/master/SOFTWARE/ESP-IDF/ESP32_PoE_Ethernet_IDFv4.0

This may also help:
https://github.com/espressif/arduino-esp32/tree/1.0.3/libraries/WiFi/examples/ETH_LAN8720

I think the key is support for the LAN8720 Ethernet chip

**Comment by sumnerboy12** [comment]
@moinmoin-sh has a branch on here (https://github.com/sumnerboy12/LSC/tree/esp-wifi/Firmware/USMArduinoFirmware) which enables support for WiFi on the ESP32. Unfortunately I don't have an ESP32 here to test or try out other fixes, so unless Moin can help with the ethernet stuff we might have to shelve this for now.

@sarreck could you try the WiFi branch I linked above and use WiFi instead of ETH?

**Comment by sarreck** [comment]
Jon has said the URC will use Wiznet W5500 so support shouldn't be an issue.

**Comment by sumnerboy12** [comment]
Yeah good point. The `esp-wifi` should work for an ESP using WiFi, for ethernet we might just wait till the URC is released?

**Comment by sumnerboy12** [comment]
I am going to close this, as Jon has given me access to his repo so I will be making all changes directly on there, and any issues or bug reports should be made there also.

This issue will be redundant once we get the URC in our hands and I am able to test and update the firmware to run on it.
